spring:
  application:
    name: rest-with-java-spring-boot-udemy-v2
  
  config:
    import: ./env.properties
  
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME} 
    url: ${URL_CONN}
    username: ${USERNAME}
    password: ${PASSWORD}
    hikari:
      maximum-pool-size: 30
      connection-timeout: 50000
  
  jpa:
    hibernate:
      ddl-auto: ${DDL_OPTS}    
      show-sql: false
      open-in-view: false

  logging:
    level:
      ${PACKAGE_01}: ${LOGGING_PACKAGE}
        #root: ${LOGGING_ROOT}
