# configuracao global de cors
cors:
  originPatterns: http://localhost:8080,https://www.google.com.br,http://localhost:3000,http://www.google.com.br

file:
  upload-dir: ../../../files/

spring:
  application:
    name: rest-with-java-spring-boot-udemy-v2
  
  config:
    import: ./env.properties
  
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME} 
    url: ${URL_CONN}
    username: ${USERNAME}
    password: ${PASSWORD}
    hikari:
      maximum-pool-size: 30
      connection-timeout: 50000
  
  jpa:
    hibernate:
      ddl-auto: ${DDL_OPTS}    
      show-sql: ${HIBERNATE_SHOW_SQL}
    
    # nao e filho de hibernate
    open-in-view: ${OPEN_IN_VIEW_OPTS}
  
  # configuracoes de multpart para upload/download
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215 MB

# nao e filho de spring
logging:
  level:
    ${PACKAGE_01}: ${LOGGING_PACKAGE}
    #root: DEBUG

spring-docs:
  paths-to-match:
    - /api/**/v1/**
  swagger-ui:
    user-root-path: true
